FILES = Buffer.java Consumer.java Producer.java ProducerConsumer.java
all:
	javac $(FILES)
run:
	Java ProducerConsumer
clean:
	rm *.class
package:
	zip -r Ruffalo-Burgat-Jean-Marc-HW4.zip $(FILES) readme.txt Makefile